name: SCP Crawler

on:
  schedule:
    # 毎週日曜日午前0時（UTC）に実行（日本時間午前9時）
    - cron: '0 0 * * 0'
  workflow_dispatch: # 手動実行も可能
  
jobs:
  crawl-scp-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run SCP Crawler
      run: node github-crawler.js
      
    - name: Configure Git
      run: |
        git config --global user.name 'SCP Crawler Bot'
        git config --global user.email 'scp-crawler@github-actions.bot'
        
    - name: Commit and push results
      run: |
        git add data/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update SCP data - $(date -u +%Y%m%d%H%M%S)"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Trigger Firebase Function
      run: |
        curl -X POST "${{ secrets.FIREBASE_FUNCTION_URL }}" \
          -H "Content-Type: application/json" \
          -d '{"trigger": "github_data_update", "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"}'